; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "NSYSU"
#ifndef MyAppVersion
#define MyAppVersion "6.1.0"
#endif
#define MyAppPublisher "Daniel"
#define MyAppExeName "NSYSU.exe"

[Setup]
AppId={{A597464C-0A55-4537-B2A0-6F9DA28EB413}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=使用條款與免責聲明.txt
OutputDir=..\build\windows\installer
OutputBaseFilename=NSYSU-Windows-Setup
SetupIconFile=icon.ico
SolidCompression=yes
WizardStyle=modern
UsedUserAreasWarning=no

; 使用最高等級的 LZMA2 壓縮演算法
Compression=lzma2/ultra64
LZMADictionarySize=65536

[Languages]
Name: "chinesetraditional"; MessagesFile: "ChineseTraditional.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; 啟動 App
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
; 防火牆：允許輸入
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyAppName}"" dir=in action=allow program=""{app}\{#MyAppExeName}"" enable=yes"; Flags: runhidden
; 防火牆：允許輸出
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyAppName}"" dir=out action=allow program=""{app}\{#MyAppExeName}"" enable=yes"; Flags: runhidden

[UninstallRun]
; 移除防火牆規則
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName}"" program=""{app}\{#MyAppExeName}"""; Flags: runhidden; RunOnceId: "RemoveFirewallRule"

[UninstallDelete]
; 刪除崩潰紀錄檔
Type: files; Name: "{localappdata}\CrashDumps\{#MyAppName}*.dmp"

[Registry]
; 停用本機崩潰傾印，解除安裝時自動刪除此機碼
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\{#MyAppExeName}"; ValueType: dword; ValueName: "DumpCount"; ValueData: "0"; Flags: uninsdeletekey

[Code]
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Path1: string;
  Path2: string;
  Path3: string;
begin
  if CurUninstallStep = usUninstall then
  begin
    // 新版資料夾：%APPDATA%\NSYSU
    Path1 := ExpandConstant('{userappdata}\NSYSU');

    // 舊版資料夾：%APPDATA%\com.nsysutest
    Path2 := ExpandConstant('{userappdata}\com.nsysutest');

    // 保險起見也清 com.nsysutest\NSYSU 子路徑（如果獨立存在）
    Path3 := ExpandConstant('{userappdata}\com.nsysutest\NSYSU');

    if DirExists(Path3) then
      DelTree(Path3, True, True, True);

    if DirExists(Path2) then
      DelTree(Path2, True, True, True);

    if DirExists(Path1) then
      DelTree(Path1, True, True, True);
  end;
end;
